// frontends/react-ts/src/App.tsx
import { BrowserRouter, Routes, Route } from 'react-router-dom'
import AppHeader from '@/components/AppHeader'
import AppFooter from '@/components/AppFooter'
import { lazy, Suspense } from 'react'

const HomeView = lazy(() => import('@/views/HomeView'))
const CreateView = lazy(() => import('@/views/CreateView'))
const OpenView = lazy(() => import('@/views/OpenView'))
const AboutView = lazy(() => import('@/views/AboutView'))
const AdminView = lazy(() => import('@/views/AdminView'))

export default function App() {
  return (
    <BrowserRouter>
      {/* Cyber-Glass Background Arrays */}
      <div className="ambient-glow"></div>
      <div className="background-grid"></div>

      <div className="app-container">
        <AppHeader />
        <main className="app-main">
          <Suspense fallback={<div className="cyber-glass center-card text-center">页面加载中...</div>}>
            <Routes>
              <Route path="/" element={<HomeView />} />
              <Route path="/create" element={<CreateView />} />
              <Route path="/open/:code?" element={<OpenView />} />
              <Route path="/about" element={<AboutView />} />
              <Route path="/admin" element={<AdminView />} />
            </Routes>
          </Suspense>
        </main>
        <AppFooter />
      </div>
    </BrowserRouter>
  )
}

// frontends/vue3-ts/src/App.vue
<template>
  <div class="ambient-glow"></div>
  <div class="background-grid"></div>

  <div class="app-container">
    <AppHeader />
    <main class="app-main">
      <RouterView v-slot="{ Component }">
        <Suspense>
          <component :is="Component" />
          <template #fallback>
            <div class="cyber-glass center-card text-center route-loading">页面加载中...</div>
          </template>
        </Suspense>
      </RouterView>
    </main>
    <AppFooter />
  </div>
</template>

<script setup lang="ts">
import { RouterView } from 'vue-router'
import { Suspense } from 'vue'
import AppHeader from '@/components/AppHeader.vue'
import AppFooter from '@/components/AppFooter.vue'
</script>

<style scoped>
.app-container {
  display: flex;
  flex-direction: column;
  min-height: 100vh;
}

.route-loading {
  padding: 2rem;
}
</style>
