// frontends/angular-ts/src/app/views/home/home.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { RouterLink } from '@angular/router';
import { TechStackService } from '../../services/tech-stack.service';
import { simplifyTechLabel } from '../../utils/tech-stack';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './home.component.html',
  styleUrl: './home.component.css',
})
export class HomeComponent implements OnInit {
  private readonly techStackService = inject(TechStackService);

  readonly techStack = this.techStackService.techStack;
  readonly loading = this.techStackService.loading;
  readonly error = this.techStackService.error;
  ngOnInit(): void {
    this.techStackService.load();
  }

  get techItems() {
    const techStack = this.techStack();
    const fallback = this.error() || !techStack;

    return [
      { src: '/frontend.svg', alt: 'Angular Logo', label: 'Angular' },
      { src: '/frontend-language.svg', alt: 'TypeScript Logo', label: 'TypeScript' },
      {
        src: '/tech-logos/backend.svg',
        alt: '后端框架 Logo',
        label: this.loading() ? '...' : fallback ? '?' : simplifyTechLabel(techStack!.framework),
      },
      {
        src: '/tech-logos/language.svg',
        alt: '后端语言 Logo',
        label: this.loading() ? '加载中' : fallback ? '?' : simplifyTechLabel(techStack!.language),
      },
      {
        src: '/tech-logos/database.svg',
        alt: '数据库 Logo',
        label: this.loading() ? '...' : fallback ? '?' : simplifyTechLabel(techStack!.database),
      },
    ];
  }
}

<section id="view-home" class="view active">
  <div class="hero-section">
    <div class="hero-badge">TIMECAPSULE SYSTEM</div>
    <h1 class="hero-title">封存此刻 <span class="text-glow">开启未来</span></h1>
    <p class="hero-subtitle">将您的寄语、秘密或愿景封装于时间胶囊中，直到指定的未来时刻才能被访问。</p>

    <div class="action-cards">
      <a routerLink="/create" class="action-card cyber-glass action-card-link" aria-label="创建胶囊">
        <div class="card-icon cyan-glow">
          <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M12 5v14M5 12h14"></path>
          </svg>
        </div>
        <h3>创建胶囊</h3>
        <p>封存此刻寄语，投递给未来的自己</p>
      </a>

      <a routerLink="/open" class="action-card cyber-glass action-card-link" aria-label="开启胶囊">
        <div class="card-icon magenta-glow">
          <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <circle cx="11" cy="11" r="8"></circle>
            <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
          </svg>
        </div>
        <h3>开启胶囊</h3>
        <p>输入提取凭据，唤醒沉睡的时间印记</p>
      </a>
    </div>

    <div class="tech-stack-simple cyber-glass">
      <h4 class="stack-title">TECHNOLOGY STACK</h4>
      <div class="tech-logos-grid text-center">
        @for (item of techItems; track item.alt + item.label) {
          <div class="tech-item" [title]="item.label">
            <img [src]="item.src" class="stack-icon" [alt]="item.alt" />
            <span>{{ item.label }}</span>
          </div>
        }
      </div>
    </div>
  </div>
</section>

// frontends/svelte-ts/src/views/Home.svelte
<script lang="ts">
  import ObjectLink from "@/lib/components/Link.svelte";
  import { techStackState } from '../lib/tech-stack-state.svelte';
  import { simplifyTechLabel } from '../lib/tech-stack-utils';

  const Link = ObjectLink;

  $: techItems = [
    { src: '/frontend.svg', alt: 'Svelte Logo', label: 'Svelte' },
    { src: '/frontend-language.svg', alt: 'TypeScript Logo', label: 'TypeScript' },
    {
      src: '/tech-logos/backend.svg',
      alt: '后端框架 Logo',
      label: techStackState.loading ? '...' : techStackState.error || !techStackState.techStack ? '?' : simplifyTechLabel(techStackState.techStack.framework),
    },
    {
      src: '/tech-logos/language.svg',
      alt: '后端语言 Logo',
      label: techStackState.loading ? '加载中' : techStackState.error || !techStackState.techStack ? '?' : simplifyTechLabel(techStackState.techStack.language),
    },
    {
      src: '/tech-logos/database.svg',
      alt: '数据库 Logo',
      label: techStackState.loading ? '...' : techStackState.error || !techStackState.techStack ? '?' : simplifyTechLabel(techStackState.techStack.database),
    },
  ];
</script>

<section id="view-home" class="view active">
  <div class="hero-section">
    <div class="hero-badge">TIMECAPSULE SYSTEM</div>
    <h1 class="hero-title">封存此刻 <span class="text-glow">开启未来</span></h1>
    <p class="hero-subtitle">将您的寄语、秘密或愿景封装于时间胶囊中，直到指定的未来时刻才能被访问。</p>

    <div class="action-cards">
      <Link to="/create" class="action-card cyber-glass action-card-link">
        <div class="card-icon cyan-glow">
          <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M12 5v14M5 12h14"></path>
          </svg>
        </div>
        <h3>创建胶囊</h3>
        <p>封存此刻寄语，投递给未来的自己</p>
      </Link>

      <Link to="/open" class="action-card cyber-glass action-card-link">
        <div class="card-icon magenta-glow">
          <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <circle cx="11" cy="11" r="8"></circle>
            <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
          </svg>
        </div>
        <h3>开启胶囊</h3>
        <p>输入提取凭据，唤醒沉睡的时间印记</p>
      </Link>
    </div>

    <div class="tech-stack-simple cyber-glass">
      <h4 class="stack-title">TECHNOLOGY STACK</h4>
      <div class="tech-logos-grid text-center">
        {#each techItems as item (`${item.alt}-${item.label}`)}
          <div class="tech-item" title={item.label}>
            <img src={item.src} class="stack-icon" alt={item.alt} />
            <span>{item.label}</span>
          </div>
        {/each}
      </div>
    </div>
  </div>
</section>

<style>
  :global(.action-card-link) {
    text-decoration: none;
    color: inherit;
  }
</style>
