// frontends/svelte-ts/src/lib/components/AdminLogin.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';

  export let loading = false;
  export let error: string | null = null;

  const dispatch = createEventDispatcher<{ login: string }>();

  let password = '';

  function handleLogin() {
    if (password) {
      dispatch('login', password);
    }
  }
</script>

<form class="login-form cyber-glass" on:submit|preventDefault={handleLogin}>
  <h2 class="text-center mb-4">管理员登录</h2>
  <div class="form-group">
    <label class="input-label" for="password">密码</label>
    <input
      id="password"
      bind:value={password}
      type="password"
      class="cyber-input"
      placeholder="输入管理员密码"
      autocomplete="current-password"
    />
  </div>
  {#if error}
    <p class="input-error-text">{error}</p>
  {/if}
  <button type="submit" class="btn btn-primary submit-btn" disabled={loading || !password}>
    {loading ? '登录中...' : '登录'}
  </button>
</form>

<style>
  .login-form {
    max-width: 400px;
    margin: 0 auto;
  }

  .form-group {
    margin-bottom: 1.5rem;
  }

  .submit-btn {
    width: 100%;
  }
</style>

// fullstacks/nuxt-ts/components/AdminLogin.vue
<template>
  <form class="login-form cyber-glass" @submit.prevent="handleLogin">
    <h2 class="text-center mb-4">管理员登录</h2>
    <div class="form-group">
      <label for="password">管理员密码</label>
      <input
        id="password"
        v-model="password"
        type="password"
        class="cyber-input text-center mono-font"
        placeholder="******"
        autocomplete="current-password"
      />
    </div>
    <p v-if="error" class="input-error-text">{{ error }}</p>
    <button type="submit" class="btn btn-primary submit-btn" :disabled="loading || !password">
      {{ loading ? '登录中...' : '登录' }}
    </button>
  </form>
</template>

<script setup lang="ts">
import { ref } from 'vue'

defineProps<{
  loading?: boolean
  error?: string | null
}>()

const emit = defineEmits<{
  login: [password: string]
}>()

const password = ref('')

function handleLogin() {
  if (password.value) {
    emit('login', password.value)
  }
}
</script>

<style scoped>
.login-form {
  max-width: 450px;
  margin: 0 auto;
}

.form-group {
  margin-bottom: 1.5rem;
}

.submit-btn {
  width: 100%;
  justify-content: center;
}
</style>
