// fullstacks/nuxt-ts/pages/admin.vue
<template>
  <div class="page">
    <div class="container">
      <div class="page-header">
        <h1>管理后台</h1>
      </div>

      <AdminLogin v-if="!isLoggedIn" :loading="loading" :error="error" @login="handleLogin" />

      <template v-else>
        <div class="admin-bar flex items-center justify-between mb-6">
          <p class="text-sm text-secondary">已登录为管理员</p>
          <button class="btn btn-secondary btn-sm" @click="logout">退出登录</button>
        </div>

        <CapsuleTable
          :capsules="capsules"
          :page-info="pageInfo"
          :loading="loading"
          @delete="handleDelete"
          @page="fetchCapsules"
          @refresh="() => fetchCapsules(pageInfo.number)"
        />

        <ConfirmDialog
          :visible="showDeleteConfirm"
          title="确认删除"
          :message="`确定要删除胶囊 ${deleteTarget} 吗？此操作不可恢复。`"
          @confirm="confirmDelete"
          @cancel="showDeleteConfirm = false"
        />
      </template>
    </div>
  </div>
</template>

<script setup lang="ts">
definePageMeta({
  middleware: ['admin-session'],
})

useSeoMeta({
  title: '管理后台 - 时间胶囊-Nuxt',
  description: 'Nuxt 全栈实现的管理员登录与胶囊管理页面',
})

const {
  capsules,
  pageInfo,
  loading,
  error,
  isLoggedIn,
  login,
  logout,
  fetchCapsules,
  deleteCapsule,
} = useAdmin()

const showDeleteConfirm = ref(false)
const deleteTarget = ref('')

async function handleLogin(password: string) {
  try {
    await login(password)
    await fetchCapsules(0)
  } catch {
    // composable handles error
  }
}

function handleDelete(code: string) {
  deleteTarget.value = code
  showDeleteConfirm.value = true
}

async function confirmDelete() {
  showDeleteConfirm.value = false
  await deleteCapsule(deleteTarget.value)
}
</script>

// frontends/angular-ts/src/app/views/admin/admin.component.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { AdminService } from '../../services/admin.service';
import { AdminLoginComponent } from '../../components/admin-login/admin-login.component';
import { CapsuleTableComponent } from '../../components/capsule-table/capsule-table.component';
import { ConfirmDialogComponent } from '../../components/confirm-dialog/confirm-dialog.component';

@Component({
  selector: 'app-admin',
  standalone: true,
  imports: [AdminLoginComponent, CapsuleTableComponent, ConfirmDialogComponent],
  templateUrl: './admin.component.html',
  styleUrl: './admin.component.css',
})
export class AdminComponent implements OnInit {
  protected readonly adminService = inject(AdminService);

  showDeleteConfirm = signal(false);
  deleteTarget = signal('');

  ngOnInit(): void {
    if (this.adminService.isLoggedIn()) {
      this.adminService.fetchCapsules();
    }
  }

  async handleLogin(password: string): Promise<void> {
    try {
      await this.adminService.login(password);
      await this.adminService.fetchCapsules();
    } catch {
      // error state handled in service
    }
  }

  handleDelete(code: string): void {
    this.deleteTarget.set(code);
    this.showDeleteConfirm.set(true);
  }

  async confirmDelete(): Promise<void> {
    this.showDeleteConfirm.set(false);
    await this.adminService.deleteCapsule(this.deleteTarget());
  }
}

<div class="page">
  <div class="container">
    <div class="page-header">
      <h1>管理后台</h1>
    </div>

    @if (!adminService.isLoggedIn()) {
      <app-admin-login
        [loading]="adminService.loading()"
        [error]="adminService.error()"
        (login)="handleLogin($event)"
      />
    } @else {
      <div class="admin-bar">
        <p class="admin-hint">已登录为管理员</p>
        <button type="button" class="btn btn-secondary" (click)="adminService.logout()">退出登录</button>
      </div>

      @if (adminService.error()) {
        <div class="error-banner">{{ adminService.error() }}</div>
      }

      <app-capsule-table
        [capsules]="adminService.capsules()"
        [pageInfo]="adminService.pageInfo()"
        [loading]="adminService.loading()"
        (delete)="handleDelete($event)"
        (page)="adminService.fetchCapsules($event)"
        (refresh)="adminService.fetchCapsules(adminService.pageInfo().number)"
      />

      <app-confirm-dialog
        [visible]="showDeleteConfirm()"
        title="确认删除"
        [message]="'确定要删除胶囊 ' + deleteTarget() + ' 吗？此操作不可恢复。'"
        (confirm)="confirmDelete()"
        (cancel)="showDeleteConfirm.set(false)"
      />
    }
  </div>
</div>
