// frontends/react-ts/src/views/CreateView.tsx
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import type { Capsule, CreateCapsuleForm } from '@/types'
import { useCapsule } from '@/hooks/useCapsule'
import CapsuleForm from '@/components/CapsuleForm'
import ConfirmDialog from '@/components/ConfirmDialog'

export default function CreateView() {
  const navigate = useNavigate()
  const { loading, error, create } = useCapsule()
  const [created, setCreated] = useState<Capsule | null>(null)
  const [showConfirm, setShowConfirm] = useState(false)
  const [pendingForm, setPendingForm] = useState<CreateCapsuleForm | null>(null)
  const [copied, setCopied] = useState(false)

  function handleSubmit(form: CreateCapsuleForm) {
    setPendingForm(form)
    setShowConfirm(true)
  }

  async function confirmCreate() {
    setShowConfirm(false)
    if (!pendingForm) return
    try {
      const result = await create(pendingForm)
      setCreated(result)
    } catch {
      // error handled in hook
    }
  }

  function copyCode() {
    if (created) {
      navigator.clipboard.writeText(created.code).then(() => {
        setCopied(true)
        setTimeout(() => setCopied(false), 2000)
      })
    }
  }

  if (created) {
    return (
      <section id="view-created" className="view active">
          <div className="success-container cyber-glass text-center">
              <div className="status-icon success-glow">
                  <svg width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                      <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path>
                      <polyline points="22 4 12 14.01 9 11.01"></polyline>
                  </svg>
              </div>
              <h2>胶囊创建成功</h2>
              <p>您的时间胶囊已成功封存。</p>
              <div className="capsule-key-box">
                  <span className="label">胶囊码</span>
                  <div className="code-display mono-font glow-text">{created.code}</div>
                  <button className="btn btn-icon btn-copy" onClick={copyCode} aria-label="Copy code">
                      {copied ? '✓' : (
                        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                            <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
                            <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
                        </svg>
                      )}
                  </button>
              </div>
              <div
                className="cyber-glass"
                style={{
                  marginTop: '1.25rem',
                  padding: '1rem 1.25rem',
                  borderColor: 'rgba(0, 240, 255, 0.28)',
                  background: 'rgba(0, 240, 255, 0.07)',
                  textAlign: 'left',
                }}
              >
                <div className="mono-font" style={{ color: 'var(--cyan)', fontSize: '0.8rem', marginBottom: '0.4rem' }}>
                  SAVE THIS CODE
                </div>
                <div style={{ margin: 0, color: 'var(--text-primary)', lineHeight: 1.7 }}>
                  请务必妥善保存胶囊码。它是开启此胶囊的唯一凭证，丢失后将无法找回或补发。
                </div>
              </div>
              <button className="btn btn-outline mt-6" onClick={() => navigate('/')}>返回首页</button>
          </div>
      </section>
    )
  }

  return (
    <section id="view-create" className="view active">
        <div className="view-header">
            <button className="btn-back" onClick={() => navigate('/')}>
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <line x1="19" y1="12" x2="5" y2="12"></line>
                    <polyline points="12 19 5 12 12 5"></polyline>
                </svg>
                返回
            </button>
            <h2>创建时间胶囊</h2>
        </div>

        {error && <div style={{ color: 'var(--magenta)', marginBottom: '1rem', textAlign: 'center' }}>{error}</div>}
        <CapsuleForm loading={loading} onSubmit={handleSubmit} />
        <ConfirmDialog
          visible={showConfirm}
          title="确认创建"
          message={`确定要创建标题为「${pendingForm?.title}」的时间胶囊吗？\n\n胶囊一经创建，内容和解锁时间将无法修改，也无法删除。`}
          onConfirm={confirmCreate}
          onCancel={() => setShowConfirm(false)}
        />
    </section>
  )
}

// frontends/vue3-ts/src/views/CreateView.vue
<template>
  <section v-if="created" id="view-created" class="view active">
    <div class="success-container cyber-glass text-center">
      <div class="status-icon success-glow">
        <svg width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path>
          <polyline points="22 4 12 14.01 9 11.01"></polyline>
        </svg>
      </div>
      <h2>胶囊创建成功</h2>
      <p>您的时间胶囊已成功封存。</p>
      <div class="capsule-key-box">
        <span class="label">胶囊码</span>
        <div class="code-display mono-font glow-text">{{ created.code }}</div>
        <button class="btn btn-icon btn-copy" @click="copyCode" aria-label="Copy code">
          <span v-if="copied">✓</span>
          <svg v-else width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
            <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
          </svg>
        </button>
      </div>
      <div class="cyber-glass code-notice">
        <div class="mono-font notice-label">SAVE THIS CODE</div>
        <div class="code-notice-text">请务必妥善保存胶囊码。它是开启此胶囊的唯一凭证，丢失后将无法找回或补发。</div>
      </div>
      <button class="btn btn-outline mt-6" @click="router.push('/')">返回首页</button>
    </div>
  </section>

  <section v-else id="view-create" class="view active">
    <div class="view-header">
      <button class="btn-back" @click="router.push('/')">
        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <line x1="19" y1="12" x2="5" y2="12"></line>
          <polyline points="12 19 5 12 12 5"></polyline>
        </svg>
        返回
      </button>
      <h2>创建时间胶囊</h2>
    </div>

    <div v-if="error" class="create-error">{{ error }}</div>
    <CapsuleForm :loading="loading" @submit="handleSubmit" />
    <ConfirmDialog
      :visible="showConfirm"
      title="确认创建"
      :message="`确定要创建标题为「${pendingForm?.title}」的时间胶囊吗？\n\n胶囊一经创建，内容和解锁时间将无法修改，也无法删除。`"
      @confirm="confirmCreate"
      @cancel="showConfirm = false"
    />
  </section>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import type { Capsule, CreateCapsuleForm } from '@/types'
import { useCapsule } from '@/composables/useCapsule'
import CapsuleForm from '@/components/CapsuleForm.vue'
import ConfirmDialog from '@/components/ConfirmDialog.vue'

const router = useRouter()
const { loading, error, create } = useCapsule()
const created = ref<Capsule | null>(null)
const showConfirm = ref(false)
const pendingForm = ref<CreateCapsuleForm | null>(null)
const copied = ref(false)

function handleSubmit(form: CreateCapsuleForm) {
  pendingForm.value = form
  showConfirm.value = true
}

async function confirmCreate() {
  showConfirm.value = false
  if (!pendingForm.value) return
  try {
    const result = await create(pendingForm.value)
    created.value = result
  } catch {
    // error handled in composable
  }
}

function copyCode() {
  if (created.value) {
    navigator.clipboard.writeText(created.value.code).then(() => {
      copied.value = true
      setTimeout(() => { copied.value = false }, 2000)
    })
  }
}
</script>

<style scoped>
.create-error {
  color: var(--magenta);
  margin-bottom: 1rem;
  text-align: center;
}

.code-notice {
  margin-top: 1.25rem;
  padding: 1rem 1.25rem;
  border-color: rgba(0, 240, 255, 0.28);
  background: rgba(0, 240, 255, 0.07);
  text-align: left;
}

.notice-label {
  color: var(--cyan);
  font-size: 0.8rem;
  margin-bottom: 0.4rem;
}

.code-notice-text {
  color: var(--text-primary);
  line-height: 1.7;
}
</style>
