// fullstacks/next-ts/src/components/AppHeader.tsx
'use client'

import Link from 'next/link'
import { usePathname } from 'next/navigation'
import ThemeToggle from './ThemeToggle'

export default function AppHeader() {
  const pathname = usePathname()

  return (
    <header className="app-header">
        <Link
          href="/"
          className="logo"
          aria-label="返回首页"
          style={{ background: 'none', border: 'none', padding: 0, color: 'inherit', textDecoration: 'none' }}
        >
            <img
              src="/favicon.svg"
              alt="HelloTime"
              style={{ width: '28px', height: '28px', display: 'block' }}
            />
            <span className="text">HelloTime</span>
        </Link>
        <div className="header-actions" style={{ display: 'flex', alignItems: 'center' }}>
            <nav className="top-nav">
                <Link href="/about" className={pathname === '/about' ? 'active' : ''}>关于</Link>
            </nav>
            <ThemeToggle />
        </div>
    </header>
  )
}

// frontends/vue3-ts/src/components/AppHeader.vue
<template>
  <header class="app-header">
    <router-link to="/" class="logo logo-link" aria-label="返回首页">
      <img src="/favicon.svg" alt="HelloTime" class="logo-img" />
      <span class="logo-text">HelloTime</span>
    </router-link>
    <div class="header-actions">
      <nav class="top-nav">
        <router-link to="/about" active-class="active">关于</router-link>
      </nav>
      <div class="theme-toggle-wrap">
        <ThemeToggle />
      </div>
    </div>
  </header>
</template>

<script setup lang="ts">
import ThemeToggle from './ThemeToggle.vue'
</script>

<style scoped>
.logo-img {
  width: 28px;
  height: 28px;
  display: block;
}

.logo-text {
  color: inherit;
}

.logo-link {
  text-decoration: none;
  color: inherit;
}

.header-actions {
  display: flex;
  align-items: center;
}

.theme-toggle-wrap {
  display: flex;
  align-items: center;
}

@media (max-width: 480px) {
  .logo-text {
    display: none;
  }
}
</style>
